/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/airplane/model2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Airplane(props) {
  const { nodes, materials } = useGLTF('./models/airplane/model2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Jet_Cube024_1.geometry} material={materials['455A64']} />
      <mesh geometry={nodes.Jet_Cube024_1_1.geometry} material={materials['80DEEA']} />
      <mesh geometry={nodes.Jet_Cube024_1_2.geometry} material={materials['1A1A1A']} />
      <mesh geometry={nodes.Jet_Cube024_1_3.geometry} material={materials['78909C']} />
    </group>
  )
}

useGLTF.preload('./models/airplane/model2.glb')
